# команда перезагрузки конфига /blockphysicslimiter (право: blockphysicslimiter.command)

# лимит числа обновлений блоков, в это число входит все: поршни, redstone, рост урожая и вообще любые изменения в мире
limit: 2500
# лимит, при котором плагин начнет удалять блоки
limit-break-block: 25000
# радиус в чанках, в которых будет действовать лимит
radius-chunks: 10
# количество тиков, в течении которого действует лимит
ticks: 10